import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
    // Coverage is wired at the settings level on purpose: the aggregation plugin
    // instruments every module automatically (including Android variants) and creates
    // a single set of root tasks — koverXmlReport, koverHtmlReport, koverVerify.
    // Settings scripts cannot read gradle/libs.versions.toml, so this version is the
    // single source of truth for Kover.
    id("org.jetbrains.kotlinx.kover.aggregation") version "0.9.9"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "noveliq-android"
include(":app")
include(":data")
include(":domain")
include(":presentation")
include(":playback")

// ---------------------------------------------------------------------------
// Coverage configuration
//
// Target: 90-100% line coverage on unit-testable code.
//
// "Unit-testable" is doing real work in that sentence. The excludes below remove
// code that a JVM unit test structurally cannot reach, so the percentage reflects
// logic you actually chose not to test rather than framework glue you never could.
// Without them, 90% is unreachable and the number stops meaning anything.
// ---------------------------------------------------------------------------
val coverageFloors =
    mapOf(
        // Pure Kotlin, no Android dependencies — this is where the 90% push starts
        // and where the bar should always be highest.
        ":domain" to 0,
        ":data" to 0,
        ":playback" to 0,
        ":presentation" to 0,
        ":app" to 0,
    )

kover {
    enableCoverage()

    reports {
        excludedClasses.addAll(
            // Generated by KSP: Hilt, Dagger, Room, Compose.
            "*_Factory",
            "*_Factory\$*",
            "*_MembersInjector",
            "*_HiltModules*",
            "*_GeneratedInjector",
            "Hilt_*",
            "*.Hilt_*",
            "hilt_aggregated_deps.*",
            "dagger.hilt.*",
            "*_Impl",
            "*_Impl\$*",
            "*ComposableSingletons*",
            // Android build artifacts.
            "*.BuildConfig",
            "*.R",
            "*.R\$*",
            // Framework entry points. These are covered by instrumentation tests
            // (see the nightly workflow), not by JVM unit tests.
            "*.NoveliqApplication",
            "*Activity",
            "*Activity\$*",
            "*.PlaybackService",
            // Hilt @Module objects are declarative wiring with no branching logic.
            "*.di.*Module",
            "*.PlaybackModule",
        )

        // @Composable UI is verified by Compose UI tests on a device, not by JVM
        // unit tests. 33 of the 55 files in :presentation are composables, so
        // including them would cap the achievable number well below 90%.
        // ViewModels, use cases and mappers stay in scope — that is the logic that
        // matters here. Drop this block if you later adopt Robolectric-backed
        // Compose tests and want composables inside the same target.
        excludesAnnotatedBy.addAll(
            "androidx.compose.runtime.Composable",
            "androidx.compose.ui.tooling.preview.Preview",
        )

        verify {
            // Fail the build, don't just warn — a coverage floor that only warns
            // is a coverage floor that silently erodes.
            warningInsteadOfFailure.set(false)

            // Per-module ratchet. Raise a floor every time a module's real coverage
            // clears it with room to spare; never lower one. Read the current numbers
            // from the job summary that CI posts on each run.
            eachProjectRule {
                val floor = coverageFloors[projectPath] ?: 0
                bound {
                    minValue.set(floor)
                    coverageUnits.set(CoverageUnit.LINE)
                    aggregationForGroup.set(AggregationType.COVERED_PERCENTAGE)
                }
            }

            // Whole-codebase floor. This is the number to drive to 90.
            rule("Aggregate line coverage") {
                bound {
                    minValue.set(0)
                    coverageUnits.set(CoverageUnit.LINE)
                    aggregationForGroup.set(AggregationType.COVERED_PERCENTAGE)
                }
            }
        }
    }
}
